DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
	SEQ NUMBER(5),
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50),
	EMAIL VARCHAR2(50),
	HIREDATE VARCHAR2(50)
);

CREATE SEQUENCE SEQ_EMPLOYEE
START WITH 1
INCREMENT BY 1;

SELECT * FROM EMPLOYEE;